{% set name = "lfortran" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://lfortran.github.io/tarballs/release/{{ name }}-{{ version }}.tar.gz
  sha256: b642b8ea5a5d90acf90f6acbf967257d483b76260d59bb49320b4551bb1dcece
  patches:
    - lto.patch

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
  host:
    - xeus >=0.24.1,<0.25
    - llvmdev =9.0.1
    - xtl
    - nlohmann_json
    - cppzmq

test:
  commands:
    - test -f ${PREFIX}/bin/lfortran  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\lfortran.exe (exit 0) else (exit 1)  # [win]
    - lfortran --help
    - lfortran --version

about:
  home: https://lfortran.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  doc_url: https://docs.lfortran.org/
  dev_url: https://gitlab.com/lfortran/lfortran

extra:
  recipe-maintainers:
    - certik
