{% set name = "lfortran" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://lfortran.github.io/tarballs/release/{{ name }}-{{ version }}.tar.gz
  sha256: ee4b4afefe6c6b2e85a7a51a21888ef1b00ac17414747d9e2f1ef8fc3fb5ac9f
  patches:
    - lto.patch
    - custom.patch

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
    - xeus =3.0.5       # [build_platform != target_platform]
    - xeus-zmq =1.0.2   # [build_platform != target_platform]
    - llvmdev =15.0.7   # [build_platform != target_platform]
    - xtl               # [build_platform != target_platform]
    - nlohmann_json     # [build_platform != target_platform]
    - cppzmq            # [build_platform != target_platform]
    - zlib              # [build_platform != target_platform]
  host:
    - xeus =3.0.5
    - xeus-zmq =1.0.2
    - llvmdev =11.1.0   # [osx and x86_64]
    - llvmdev =15.0.7   # [not osx or not x86_64]
    - xtl
    - nlohmann_json
    - cppzmq
    - zlib
  run:
    # xeus breaks abi compatibility in patch versions even though
    # run_exports say otherwise in https://github.com/conda-forge/xeus-feedstock/blob/0896038be810da2944ebcb612e22886815ea691e/recipe/meta.yaml#L18
    - {{ pin_compatible("xeus", max_pin="x.x.x") }}  # [win]

test:
  requires:
    - jupyter
  commands:
    - test -f ${PREFIX}/bin/lfortran  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\lfortran.exe exit 1  # [win]
    - lfortran --help
    - lfortran --version
    - jupyter kernelspec list --json
      # This fails if the `fortran` spec is not installed
    - jupyter kernelspec remove -f fortran

about:
  home: https://lfortran.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  doc_url: https://docs.lfortran.org/
  dev_url: https://github.com/lfortran/lfortran

extra:
  recipe-maintainers:
    - certik
