{% set name = "lfortran" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://lfortran.github.io/tarballs/release/{{ name }}-{{ version }}.tar.gz
  sha256: 52a8a5621041e6d49cef48de6b2eb0708d71a041b53ce10000152e06667fa84c

build:
  number: 0
  script:
    - set CMAKE_GENERATOR=   # [win]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make   # [not win]
  host:
    - python
    - pip
    - scikit-build
    - setuptools
  run:
    - python
    - llvmlite
    - antlr-python-runtime
    - prompt_toolkit

test:
  imports:
    - lfortran
  requires:
    - pytest
  commands:
    - pytest --pyargs lfortran
    - lfort --help

about:
  home: https://lfortran.org
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  doc_url: https://docs.lfortran.org/
  dev_url: https://gitlab.com/lfortran/lfortran

extra:
  recipe-maintainers:
    - certik
