{% set name = "lfortran" %}
{% set version = "0.41.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/lfortran/lfortran/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
    sha256: edc37baa0714b283e6b36369d5bde85ad8bc6a6d335e9ded33ffea27496e1306
    patches:
    - macos_time.patch
    - lsp.patch
    - llvm_sym.patch
  - git_url: https://github.com/emscripten-core/emsdk.git
    folder: emsdk

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake =3.21.1
    - make   # [unix]
    - xeus =5.1.0       # [build_platform != target_platform]
    - xeus-zmq =3.0.0   # [build_platform != target_platform]
    - llvmdev =16.0.6   # [build_platform != target_platform]
    - nlohmann_json =3.11.3     # [build_platform != target_platform]
    - zlib              # [build_platform != target_platform]
    - zstd-static =1.5.5  # [build_platform != target_platform]
    - nodejs
  host:
    - xeus =5.1.0
    - xeus-zmq =3.0.0
    - llvmdev =16.0.6
    - nlohmann_json =3.11.3
    - zlib
    - zstd-static =1.5.5
  run:
    # xeus breaks abi compatibility in patch versions even though
    # run_exports say otherwise in https://github.com/conda-forge/xeus-feedstock/blob/0896038be810da2944ebcb612e22886815ea691e/recipe/meta.yaml#L18
    - {{ pin_compatible("xeus", max_pin="x.x.x") }}  # [win]

test:
  requires:
    - jupyter
  commands:
    - test -f ${PREFIX}/bin/lfortran  # [unix]
    - if not exist %LIBRARY_PREFIX%\bin\lfortran.exe exit 1  # [win]
    - lfortran --help
    - lfortran --version
    - jupyter kernelspec list --json
      # This fails if the `fortran` spec is not installed
    - jupyter kernelspec remove -f fortran

about:
  home: https://lfortran.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Modern interactive LLVM-based Fortran compiler
  description: |
    LFortran is a modern open-source (BSD licensed) interactive Fortran
    compiler built on top of LLVM. It can execute user's code interactively to
    allow exploratory work (much like Python, MATLAB or Julia) as well as
    compile to binaries with the goal to run user’s code on modern
    architectures such as multi-core CPUs and GPUs.
  doc_url: https://docs.lfortran.org/
  dev_url: https://github.com/lfortran/lfortran

extra:
  recipe-maintainers:
    - certik
    - Shaikh-Ubaid
